export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_QTY = "CLEAR_CART";
export const FETCH_CART = "FETCH_CART";
export const FETCH_CART_REQUEST = "FETCH_CART_LOADING";
export const FETCH_CART_SUCCESS = "  FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE = "  FETCH_CART_FAILURE";
